# Generated by Django 3.1.2 on 2020-10-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
