# Generated by Django 3.1.2 on 2020-10-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
